CIProjectweb/CIProjectweb/Controllers/MissionController.cs
using CIProjectweb.Entities.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using CIProjectweb.Entities.DataModels;
using Microsoft.AspNetCore.Mvc;
using CIProjectweb.Models;
using System.Text.Json;
using CIProjectweb.Repository.Repository.Interface;

namespace CI_Plateform.Controllers
{
    public class MissionController : Controller
    {
        private readonly ILogin _objILogin;
        private readonly IUserInterface _objUserInterface;
       


        private readonly ILogger<MissionController> _logger;
       
        private readonly CIDbContext _db;



        public MissionController(ILogger<MissionController> logger, CIDbContext db, ILogin objLogin, IUserInterface objUserInterface)
        {
            _logger = logger;
            _objILogin = objLogin;
            _objUserInterface = objUserInterface;
            _db = db;
        }




        public IActionResult LandingPage(int pg = 1)
        {
            try
            {
                var userId = HttpContext.Session.GetString("UserId");

                int u_id = int.Parse(userId);
                MissionListingModel model = new MissionListingModel();

                #region Fill Country Drop-down
                List<SelectListItem> listCountry = new List<SelectListItem>();
                var tempCountry = _db.Countries.Where(m => m.DeletedAt == null).ToList();
                foreach (var country in tempCountry)
                {
                    listCountry.Add(new SelectListItem() { Text = country.Name, Value = country.CountryId.ToString() });
                }
                model.countries = listCountry;
                // ViewBag.listOfCountry = new SelectList(listCountry);
                // ViewBag.listOfCountry = ;
                #endregion Fill Country Drop-down

                #region Fill City Drop-down
                List<SelectListItem> listCity = new List<SelectListItem>();
                var tempCity = _db.Cities.Where(m => m.DeletedAt == null).ToList();
                foreach (var city in tempCity)
                {
                    listCity.Add(new SelectListItem() { Text = city.Name, Value = city.CityId.ToString() });
                }
                model.cities = listCity;
                #endregion Fill City Drop-down

                #region Fill MissionTheme Drop-down
                List<SelectListItem> listTheme = new List<SelectListItem>();
                var tempTheme = _db.MissionThemes.Where(m => m.DeletedAt == null).ToList();
                foreach (var theme in tempTheme)
                {
                    listTheme.Add(new SelectListItem() { Text = theme.Title, Value = theme.MissionThemeId.ToString() });
                }
                model.themes = listTheme;
                #endregion Fill MissionTheme Drop-down

                #region Fill SKills Drop-down
                List<SelectListItem> listSkills = new List<SelectListItem>();
                var tempSkills = _db.Skills.Where(m => m.DeletedAt == null).ToList();
                foreach (var skill in tempSkills)
                {
                    listSkills.Add(new SelectListItem() { Text = skill.SkillName, Value = skill.SkillId.ToString() });
                }
                model.skills = listSkills;
                #endregion Fill Skills Drop-down


                var cardData = new List<MissionCardModel>();

                var tempMission = _db.Missions.Where(m => m.DeletedAt == null && m.Status == true).ToList();
                model.TotalMission = tempMission.Count;
                foreach (var mission in tempMission)
                {

                    cardData.Add(CreateCard(mission));
                }
                model.missionsCard = cardData;

                const int pageSize = 9;
                int recsCount = tempMission.Count();
                var pager = new Pager(recsCount, pg, pageSize);
                int recSkip = (pg - 1) * pageSize;
                User user = _objILogin.GetUsers(u_id);

                ViewBag.user = user;
                var data = cardData.Skip(recSkip).Take(pager.PageSize).ToList();
                model.missionsCard = data;
                this.ViewBag.Pager = pager;
                this.ViewBag.count = recsCount;
                return View(model);
            }
            catch (NullReferenceException ex)
            {
                // Handle null reference exception
                _logger.LogError(ex, "Null reference exception occurred in the try block: {0}", ex.Message);


                // Redirect to an error page with the error view model                
                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {

                var errorViewModel = new ErrorViewModel
                {

                    RequestId = ex.ToString()
                };
                // Redirect to an error page or show a generic error message
                return RedirectToAction("Error", "Home");
            }

        }


        [HttpPost]
        public IActionResult LandingPage(long?[] ids, int pg = 1)
        {

            MissionListingModel model = new MissionListingModel();
            List<SelectListItem> list = new List<SelectListItem>();
            if (ids != null && ids.Length > 0)
            {
                var cities = _db.Cities.Where(x => x.DeletedAt == null && ids.Contains(x.CountryId)).ToList();
                foreach (var item in cities)
                {
                    list.Add(new SelectListItem() { Text = item.Name, Value = item.CityId.ToString() });
                }
            }
            else
            {
                var tempCity = _db.Cities.Where(m => m.DeletedAt == null).ToList();
                foreach (var city in tempCity)
                {
                    list.Add(new SelectListItem() { Text = city.Name, Value = city.CityId.ToString() });
                }
            }

            model.cities = list;
            return Json(model.cities);
        }
        public PartialViewResult Filter(List<int>? CountryId, List<int>? CityId, List<int>? ThemeId, List<int>? SkillId, string? searchText, int? sort, string pg = "")
        {
            var userId = HttpContext.Session.GetString("UserId");
            int u_id = int.Parse(userId);
            var cardData = new List<MissionCardModel>();
            var tempMission = new List<Mission>();
            if (pg == default)
            {
                pg = "1";
            }

            #region Search
            if (CountryId.Count==0&& CityId.Count==0&& ThemeId.Count==0)
            {
                if (searchText != null)
                {
                    var missions = _db.Missions.Where(x => x.DeletedAt == null && x.Status == true && x.Title.Contains(searchText)).ToList();
                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }
            

            #endregion Search

            #region Filter Country
            if (CountryId.Count != 0)
            {
                foreach (var country in CountryId)
                {
                    List<Mission> countries;

                    if (searchText != null)
                    {
                         countries = _db.Missions.Where(x => x.DeletedAt == null && x.Status == true && x.CountryId == country && x.Title.Contains(searchText)).ToList();
                    }
                    else
                    {
                         countries = _db.Missions.Where(x => x.DeletedAt == null && x.Status == true && x.CountryId == country).ToList();
                    }
                    if (countries.Count==0)
                    {
                        return PartialView("_nomissionFound");
                    }
                    foreach (var c in countries)
                    {
                        bool temp = tempMission.Any(x => x.MissionId == c.MissionId);
                        if (temp == false)
                        {
                            tempMission.Add(c);
                        }
                    }
                    
                }
            }
            #endregion Filter Country

            #region Filter City
            if (CityId.Count != 0)
            {
                foreach (var city in CityId)
                {
                    List<Mission> cities;
                    if (searchText != null)
                    {
                        cities = _db.Missions.Where(x => x.DeletedAt == null && x.Status == true && x.CityId == city && x.Title.Contains(searchText)).ToList();
                    }
                    else
                    {
                         cities = _db.Missions.Where(x => x.DeletedAt == null && x.Status == true && x.CityId == city).ToList();
                    }
                    if (cities.Count == 0)
                    {
                        return PartialView("_nomissionFound");
                    }
                    foreach (var c in cities)
                    {
                        bool temp = tempMission.Any(x => x.MissionId == c.MissionId);
                        if (temp == false)
                        {
                            tempMission.Add(c);
                        }
                    }
                   
                }
            }
            #endregion Filter City

            #region Filter Themes
            if (ThemeId.Count != 0)
            {
                foreach (var theme in ThemeId)
                {
                    var themes = _db.Missions.Where(x => x.DeletedAt == null && x.Status == true && x.ThemeId == theme).ToList();
                    if (themes.Count==0)
                    {

CIProjectweb/CIProjectweb/Views/Mission/LandingPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Login Page";
}
@{
    var Count = ViewBag.count;
    Pager pager = new Pager();

    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}
 <link rel="stylesheet" href="~/css/custom.css"  />
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
@model CIProjectweb.Entities.ViewModels.MissionListingModel

<div class="mt-md-3 mb-md-3 d-flex justify-content-center">

    <div id="divCountryDiv"></div>
    <div id="divCityDiv"></div>
    <div id="divThemeDiv"></div>
    <div id="divSkillDiv"></div>

    <a class="ms-2 d-none clearAllFilter" style="text-decoration: none; color:black;" asp-controller="Mission" asp-action="LandingPage">
        Clear all
    </a>
</div>
<br />
<form asp-action="LandingPage" asp-controller="Home" method="post">

    <div class="container-lg grid-container" id="card">
        <div id="missionGrid">
            <div class="row mb-5" id="missionpartialView">

              

            </div>
        </div>

    </div>

    
</form>



<script>
        $(function () {
        var PlaceHolderElement = $('#PlaceHolderHere');
        $('button[data-toggle="ajax-modal"]').click(function (event) {

            var url = $(this).data('url');
            var decodeUrl = decodeURIComponent(url);
            console.log(url);
            $.get(decodeUrl).done(function (data) {
                PlaceHolderElement.html(data);
                PlaceHolderElement.find('.modal').modal('show');
            })
        })

        PlaceHolderElement.on('click', '[data-bs-save="modal"]', function (event) {

            var formData = new FormData($('#modalForm').get(0));
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');
            $.ajax({
                url: "/Mission/" + actionUrl,
                type: "POST",
                data: formData,
                processData: false,
                contentType: false,
                dataType: "json",
                success: function (data) {
                    PlaceHolderElement.find('.modal').modal('hide');
                }

            })
            PlaceHolderElement.find('.modal').modal('hide');
        })

    })
</script>

<script>

    function showList() {

  var $gridCont = $(".grid-container");
  $(".hrbtn-img").addClass("hr-btn");
  $(".card-img-top").addClass("card-img-top-listview");
  $gridCont.addClass("list-view");
}

function gridList() {
  
  var $gridCont = $(".grid-container");
  $(".hrbtn-img").removeClass("hr-btn");
  $(".card-img-top").removeClass("card-img-top-listview");
  $gridCont.removeClass("list-view");
}

$(document).on("click", ".btn-grid", gridList);
$(document).on("click", ".btn-list", showList);

 //Check if there is a preference set in local storage

    
////function showList(e) {
////    var $gridCont = $(".grid-container");
    
////        $gridCont.addClass("list-view");
  
         
////    }
////        function gridList(e) {
////        var $gridCont = $(".grid-container");
////        e.preventDefault();

////        $gridCont.removeClass("list-view");
////    }

////        $(document).on("click", ".btn-grid", gridList);
////        $(document).on("click", ".btn-list", showList);
//var viewPreference = localStorage.getItem('viewPreference');

//if (viewPreference === 'list') {
//  showList();
//} else if (viewPreference === 'grid') {
//  gridList();
//}
//    function showList(e) {
//       localStorage.setItem('viewPreference', 'List');
//        var $gridCont = $(".grid-container");

//        // e.preventDefault();
//        $(".hrbtn-img").addClass("hr-btn");
//        $(".card-img-top").addClass("card-img-top-listview");
//          $gridCont.addClass("list-view");
//    }
//    function gridList(e) {
//          localStorage.setItem('viewPreference', 'grid');
//        var $gridCont = $(".grid-container");
//        e.preventDefault();
//        $(".hrbtn-img").removeClass("hr-btn");
//        $(".card-img-top").removeClass("card-img-top-listview");
//        $gridCont.removeClass("list-view");
//    }
    
//    $(document).on("click", ".btn-grid", gridList);
//    $(document).on("click", ".btn-list", showList);


</script>
<script type="text/javascript">
    function PagerClick(index) {
        document.getElementById("hfCurrentPageIndex").value = index;
        document.forms[0].submit();
    }
</script>
<script>


    function redirectToMission(id) {
        window.location.href = `/home/RelatedMissionPage/${id}`;
    }

</script>
<script src="~/js/relatedmission.js"></script>
<script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks the button, open the modal
     function modalcall(e) {
           var abc = e.id;
            var missionElement = document.getElementById('missionId');
            missionElement.innerHTML = abc;
          
         document.getElementById("myModal").style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    document.getElementsByClassName("close").onclick = function() {
         document.getElementById("myModal").style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
        if (event.target ==  document.getElementById("myModal")) {
            document.getElementById("myModal").style.display = "none";
        }
    }
</script>
  <script>

      setTimeout(alertFunc, 1000);
    function alertFunc() {
        VirtualSelect.init({
            ele: '#divCountry',
            dropboxWidth: '170px'
        });
        VirtualSelect.init({
            ele: '#divCity',
            dropboxWidth: '170px'
        });
        VirtualSelect.init({
            ele: '#divTheme',
            dropboxWidth: '170px'
        });
        VirtualSelect.init({
            ele: '#divSkill',
            dropboxWidth: '170px'
        });
    }

    $(document).ready(function () {

        $("#countryDiv").change(function () {
            FilterTag("#divCountry");
            Filter();
        });
        $("#cityDiv").change(function () {
            FilterTag("#divCity");
            Filter();
        });
        $("#themeDiv").change(function () {
            FilterTag("#divTheme");
            Filter();
        });
        $("#skillDiv").change(function () {
            FilterTag("#divSkill");
            Filter();
        });
        $("#divSort").change(function () {
            Filter();
        });
    });

    function Search() {
        Filter();
    }

    function favMission(Missionid, Missionfav) {
        $.ajax({
            url: '/Mission/FavMission',
            type: 'POST',
            dataType: 'json',
            data: { id: Missionid, fav: Missionfav },
            success: function (d) {
                Filter();
            },
            error: function () {
                alert('Error');
            }
        });
    }

    function ApplyMission(MissionId) {
        $.ajax({
            url: '/Mission/ApplyMission',
            type: 'POST',
            dataType: 'json',
            data: { id: MissionId },
            success: function (d) {
                Filter();
                alert(d);
            },
            error: function () {
                alert('Error');
            }
        });
    }
    //function FilterTag(str) {
    //    var a = document.querySelector(str).getSelectedOptions();
    //    $(str + "Div").empty();
    //    $.each(a, function (i, text) {
    //        alert(i);
    //        $(str + "Div").append('<button type="button" class="btn btn-sm btn-outline-dark rounded-pill mt-1 me-2"><span class="text-wrap">' + text.label + '</span><i class="bi bi-x" onclick="closediv(i)"></i></button>');
    //    });
    //}

    function FilterTag(str) {
        var selectElement = document.querySelector(str);
        var selectedOptions = selectElement.getSelectedOptions();
        var containerElement = $(str + "Div");
        containerElement.empty();
        // Append new tags
        $.each(selectedOptions, function (i, text) {
            containerElement.append('<button type="button" class="btn btn-sm btn-outline-dark rounded-pill mt-1 me-2" id="option-' + i + '"><span class="text-wrap">' + text.label + '</span><i class="bi bi-x"></i></button>');
        });
        // Get the virtual select element
        //const virtualSelect = document.querySelector('#virtual-select');

        //// Get the options in the select list
        //const options = virtualSelect.querySelectorAll('option');

        //// Loop through each option and add a unique id to its corresponding checkbox
        //options.forEach((option, index) => {
        //    const checkbox = virtualSelect.querySelector(`[value="${option.value}"]`);
        //    checkbox.id = `checkbox-${index}`;
        //});


        containerElement.on('click', 'button i.bi-x', function () {
            // Get the index of the option to remove
            var index = $(this).parent().attr('id').split('-')[1];
            // Remove the button element
            $(this).parent().remove();
            // Remove the corresponding option from the selected options list
            document.querySelector(str).options[index].selected = false;
        });

    }


    function Filter() {
         var buttonId;
    $('.toggle').click(function() {
        buttonId = $(this).attr('id');
      // Move the alert inside the click event handler
        if (buttonId == 'list') {
            $(".hrbtn-img").addClass("hr-btn");
            $(".card-img-top").addClass("card-img-top-listview");
        } else {
            $(".hrbtn-img").removeClass("hr-btn");
            $(".card-img-top").removeClass("card-img-top-listview");
        }
    });
        
        let searchParams = new URLSearchParams(window.location.search)
        let param = searchParams.get('pg');
        var country = $("#divCountry").val();
        var city = $("#divCity").val();
        var theme = $("#divTheme").val();
        var skill = $("#divSkill").val();
        var search = $("#box").val();
        var Sort = $("#divSort").val();
        $.ajax({
            url: '/Mission/Filter',
            type: 'POST',
            dataType: 'html',
            data: { CountryId:country, CityId: city, ThemeId: theme, SkillId: skill, searchText: search, sort: Sort, pg: param},
            success: function (d) {
                $("#missionpartialView").empty();
                $("#missionpartialView").html(d);
                

                if(country.length > 0 || city.length>0 || theme.length>0)
                {
                    document.querySelector(".clearAllFilter").classList.remove("d-none");
                }
                else {
                    document.querySelector(".clearAllFilter").classList.add("d-none");
                }

            },
            error: function () {
                alert('Error');
            }
        });

    }
</script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

CIProjectweb/CIProjectweb/Views/Mission/_nomissionFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="d-flex flex-column justify-content-center mt-5">
    <div class="text-center">
       <h3>No Mission Found</h3>
    </div>
    <br />

    <div class="text-center">
                <a href="#" class="btn cardbtn mx-auto ">
                    <span>Submit New Mission</span> <img class="ms-1"
                                            src="~/lib/images/right-arrow.png">
                </a>
            </div>
</div>